// Generated by dts-bundle-generator v9.5.1

import { ESLintUtils } from '@typescript-eslint/utils';
import { Rule } from 'eslint';
import { ESLintConfig, Rules } from 'eslint-define-config';

export type _A = "error" | "warn" | "off" | 0 | 1 | 2;
export type _B<Options> = _A | [
	_A,
	Partial<Options>
];
export interface _C {
	c: _B<unknown>;
	a: _B<{
		allow: string[];
	}>;
	b: _B<unknown>;
}
export type _D = Rules & Partial<_C>;
export interface _E {
	a: () => Promise<{
		a: Rule.RuleModule | ESLintUtils.RuleModule<string, unknown[]>;
	}>;
	b?: _A;
}
export type _F = Omit<ESLintConfig, "rules"> & {
	a?: _D;
	b?: string | string[];
};
export declare function g(a?: _F): ESLintConfig;

export {};
